- vars/dspace_vars_open.yml
for VSim test and prod playbook vars
> [VSIM-21] added ORCID config to extra_configs variable

- vars/dspace_vars_open.yml
set this for both test-vsim and test-dataden
> [VSIM-32] properly set the value for dspace_handle_canonical_prefix 

- uclalib_clearcache_cantaloupe.yml
Play file to clear the filesystem cache on a cantaloupe iiif server.
> Initial commit

- uclalib_rhelupdatedownload.yml
> Add RHEL update downloadonly playbook

- README.md
First pass
TODO: 
* Move to confluence
* link n Confluence page
* Make this README more overview, leave details in Confluence
> Document individual playbooks

- triggers/jenkins-ansible_controller_configs.yml
*Summary of changes*
This playbook will be executed by Jenkins. The playbook will update fetch and pull from the master branch. `/etc/ansible` will be updated via the ansible git module.
> [LX-748] Create playbook to update/clone ansible config repo

- uclalib_vmware_snapshot.yml
Was causing the logins to fail, because of an extra space.
> Remove extraneous space

- uclalib_vmware_snapshot.yml
* Consistent with the other OS patching playboks
* Added documentation about usage and parameters
> Set default host group to unattended_yum_update

- uclalib_haproxy.yml
Add HAProxy ACL source file for library staff networks
> [LX-824] Add ACL source for lib staff networks

- uclalib_haproxy.yml
Combine similar tasks
Add proxy restart
Enable non-local IP bind (keepalived)
> Assemble ACLs prior to updating haproxy.cfg

- uclalib_rhelfirstbootvmware.yml
Including a final step in the rhel vmware provisioning process to update the operating system.
> Task to update RHEL after all roles finish running

- uclalib_rhelupdate.yml
This is with regard to [LX-801](https://jira.library.ucla.edu/browse/LX-801)
> Increase rhelupdate_serial default value to 20

- uclalib_rhelreboot.yml
Per [LX-803](https://jira.library.ucla.edu/browse/LX-803)
> Decrease reboot_timeout value to 180 seconds

- sinaimanuscripts/uclalib_sinaimanuweb.yml
- ursus/uclalib_ursusweb.yml
Percy.io requires version 10 or higher.
> Upgrade to node 10

- uclalib_virt-who.yml
> Add restart virt-who playbook

- californica/uclalib_californicasolr.yml
> Add java_platform

- oral-history/uclalib_oral-history_solr6.yml
JIRA: LX-956 Create Solr 6 instance for Oral History
Epic: APPS-466 Oral Hist. Deploy
> Add Oral History Solr playbook

- bucketeer/files/sinai-bucketeer-features-on.conf
- bucketeer/templates/bucketeer.env.j2
Needs work.
Changes:
- add dedicated feature flag config for Sinai Bucketeer
- rename image mount env vars
- add CSV mount env var
> [IIIF-981] Bucketeer: write processed CSVs to filesystem

- oral-history/uclalib_oral-history_pgsql.yml
JIRA: LX-985 / Add Postgress database creation playbook
> Add postgres playbook

- californica/uclalib_californicaweb.yml
JIRA: LX-1030 / Fix CalifornicaWeb Play to Specify Java Vendor
> Require Oracle Java

- uclalib_ansible_capdeploy.yml
JIRA: LX-1032 / Install Bundler used to Bundle Gemfile.lock
> Install versioned bundler gem

- uclalib_ansible_capdeploy.yml
JIRA: LX-1032 / Install Bundler used to Bundle Gemfile.lock
> Install bundler gem globally

- californica/uclalib_californicafedora.yml
- californica/uclalib_californicaweb.yml
LX-1036 / Install NFS client for ingest environment
> Install nfs client utilities

- californica/uclalib_californicafedora.yml
- californica/uclalib_californicasolr.yml
- californica/uclalib_californicaweb.yml
- ursus/uclalib_ursussolr.yml
- ursus/uclalib_ursusweb.yml
JIRA: LX-1041 / Limit hosts Californica/Ursus plays can run against
Epic: LX-754 / Ansible Infrastructure
> Restrict hosts to appropriate hostnames

- uclalib_avalondeploy.yml
> [APPS-666] - Playbook to deploy avalon code

- uclalib_omicron.yml
JIRA: LX-1140 / Deploy omicron app to p-u-omicron01 for acceptance testing
> Add omicron playbook

- uclalib_omicron.yml
Apply become to entire playbook
> Add firewalld role

- uclalib_vmware_snapshot_report.yml
JIRA: LX-1130 / Create VM Lingering Snapshot Report
> Add snapshot report playbook

- uclalib_rhelreboot.yml
JIRA: LX-1223 / Skip Reboot if Yum is Running
> Skip rebooting if a prohibited process is running

- uclalib_packer.yml
Only defines when not already provided
> Define default provisioner

- adhoc-rsyncd.yml
Useful for migrating data during rhel8 migration
> Add ad-hoc rsync

- sinaimanuscripts/uclalib_sinaimanuweb.yml
https://github.com/nodejs/release
18.x End-of-life 2025-04-30
> Update Node to minimum supported version

- californica/uclalib_californicasolr.yml
Other notable changes:
- apply firewall changes immediately
> Open rsync port

- uclalib_ansible_capdeploy.yml
Noteable changes:
- removed overall become
- set become for removing/adding robots.txt link prevents link from being owned as root
- elevate privileges for restarting webserver
> Adjust become: judiciously

- rhel8-migration/adhoc-rsyncd.yml
For ansible controller data migration
> Add /etc/ansible to adhoc rsync

- sinaimanuscripts/uclalib_sinaimanusolr.yml
> Remove newline

- uclalib_rhelupdate.yml
RHEL tooling no longer checks for appropriate licensing
> Remove RHEL subscription check

- uclalib_ping_all.yml
Migrated from ansible/localfiles
> Add ping play
