sandbox/www.library.ucla.edu/localdev-build.yml
sandbox/www.library.ucla.edu/requirements.yml

@cachemeoutside This adds composer/drush to the build, via the `uclalib_role_drush` role.

LX-495: Add drush role to sandbox build for www.library.ucla.edu

---

www_library/drupal_deploy_post.yml

@cachemeoutside The post-deploy drush commands need two fixes, in this PR:
* `updatedb` runs OK when there are no database updates, but needs a `-y` flag when there are updates.  This is safe when there are no updates as well.
* `features revert` should actually be `features-revert-all`, and the `-y` flag is required.  The current command is being interpreted as just `features`, which just lists the features in the output.
Thanks --Andy

Fix drush post-deploy commands

---

uclalib_rhelreboot.yml
uclalib_rhelupdate.yml

uclalib_rhelreboot.yml supports:
* Rebooting only if needs-restarting reports a reboot is required
* Cravenly refusing to reboot if needs-restarting is missing
* Verbosely refusing to reboot if /etc/no-reboot exists
* Displaying the reason for skipping (as contained in /etc/no-reboot)
* Fearlessly ignoring all of the above, and reboot anyway,
if force_reboot=True is passed
uclalib_rhelupdate.yml supports:
* Updating all installed packages, downloading if necessary

Separate rebooting to a new playbook

---

uclalib_rhelreboot.yml

Ignore_errors: True leaves with a very scary sea of red text.
Failed_when: False prevents that, and leaves a nice scroll of calming
yellow.

Replace Ignoring errors with never erroring

---

uclalib_rhelreboot.yml

failed_when: false sets .failed to false, but leaves the rc alone.
Testing on rc==1 let's us still see if a reboot is required.
I didn't catch this before the previous PR.

Fix test for reboot flags

---

uclalib_get_ssh_host_keys.yml
uclalib_push_ssh_host_keys.yml

uclalib_get_ssh_host_keys.yml:
- Uses inventory.ini as an input
- sorts hostkeys by hosthame
- Writes to /etc/ssh/ssh_known_hosts (by default)
uclalib_push_ssh_host_keys.yml:
- pushes local /etc/ssh/ssh_known_hosts to remote systems

Add playbooks for maintaining ssh host keys

---

uclalib_vmware_snapshot.yml

Required:
-  `vsphere_user` (will prompt if missing)
- `vsphere_password` (will prompt if missing)
Optional:
- `remove_snapshot`  (boolean, default false, remove snapshot)
- days_to_keep_snapshots=7 (int, default 7, older snapshots should be removed)
- `snapshot_prefix` (string, default "rhel-update", only snapshots matching this prefix will be removed)
Assumes user is in the "ad.library.ucla.edu" domain.
Passes:

Manage RHEL update snapshots

---

uclalib_swarmstackdeploy.yml

When I was separating out encrypted variables into their own vault file, I needed to change the terra groups into directories instead of the previous flat files. This broke how the deploy play referenced these files. 
To resolve this I'm explicitly stating what files need to be loaded.

Change path to var_files to include encrypted and vaulted variables

---

uclalib_vmware_snapshot.yml

When removing a snapshot, it looks for the prefix passed, not the prefix
passed plus a dash. so if you prefix with “pre-testing” it will create
“pre-testing-2020-02-21". If you make another one, “pre-testing-2” it
makes “pre-testing-2-2020-02-21". When you remove all the
“pre-testing-2” snapshots greater than zero days, it gets them both as
they both start with “pre-testing-2" instead of searching for
"pre-testing-2-".

Look for prefix plus separator

---

uclalib_haproxy.yml

The new task will read from group_vars and populate an ACL source file in `/etc/haproxy/ucla_vpn_networks`. This will allow any frontend to be able to use this ACL resource.

[LX-824] Add task to copy UCLA VPN group vars to haproxy

---

uclalib_rhelupdate.yml

Output of `subscription-manager list --consumed --pool-only` is the pool ID of the entitlement. 
If the system is not attached to any entitlement, stdout will be zero length, and the play should stop before running `yum update` task.

Insert tasks to check RHEL subscription status before yum udpate

---

uclalib_vmware_snapshot.yml

Ansible is failing to connect to vSphere:
`fatal: [p-u-calursussolrslave01.library.ucla.edu]: FAILED! => {"changed": false, "msg": "Unable to connect to vCenter or ESXi API at vc.library.ucla.edu on TCP/443: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)"}`
Bypass the SSL verficiation until the intermediate chain is updated.

Bypass SSL verification

---

uclalib_ansible_capdeploy.yml

Production systems will never allow stack traces.
Stack traces are disabled by default.
`allow_stack_trace` must be explicitly set to true(yes) to allow
stack traces in browser. Explicitly set to "false" on production
systems for documentation.

Enable Jenkins deploy to allow stack traces

---

californica/uclalib_californica_restore.yml

By default, will restore from same environment.
Ensures production restores come only from production.
This playbook offers no bypass for that assertion
New variable:
`restore_environ`: Backup to restore from. Used for migrating one
environment to another. Default: same as `server_environ`
Example migrate stage to dev:
```bash
ansible-playbook uclalib_californica_restore.yml \
-e restore_environ=stage \
-e server_environ=dev
```

Support restoring from another environment

---

uclalib_pgdbcreate.yml

@cachemeoutside @jhriv I've been investigating how to use the `uclalib_role_postgresql` role to provision a database for use-cases such as: 
* applications running on a VM that don't need the psql client installed to connect to the db
* applications running in a container where this no **host** for ansible to connect to run the play
I documented what this play is doing (and why) as comments in the play file. I tested to see if it actually is pulling in the appropriate group_vars using the `debug` task - having it display all variables associated with localhost. It did indeed show the expected pgsql variables I included in the ansible group. 
Please give this a review and let me know what you think. Do you see any issues with this method? Can you think of any reasons for this approach …

Play file to create postgresql db and user only

---

uclalib_ansible_capdeploy.yml

Bypasses `bundler's executable "bundle" conflicts with /usr/bin/bundle`
question

Force-install bundler gem

---

uclalib_rhelreboot.yml

Some systems take longer than the current three minutes.
Jenkins flags those as errors. This commit attempts to decrease the
number of false negatives.

Increase reboot timeout to five minutes

---

californica/uclalib_californica_restore.yml

A "higher" tier cannot be restored from a "lower" tier.
Prod: prod
Stage: prod, stage
Test: prod, stage, test
Dev: anything. No other validity checks are done.
JIRA: LX-1020 / Restore Fedora from Other Environments

Define tiers of environment restoration

---

uclalib_rhelupdate.yml
uclalib_rhelupdatedownload.yml

- Saves up to five seconds per invocation
- Prevents hanging when GPG signing keys are updated
Other changes:
- move become to per-task
- adjust booleans to match linter expectations
- silenced linter warnings
- we are intentional with our use of "latest"

Remove fact gathering

---

uclalib_rhelupdatedownload.yml

Some systems were skipped for some patches. Investigation pointed to outdated yum caches being the culprit.
If this fix is insufficient, a direct call too `yum makecache` is the next step in resolving it.
JIRA: LX-1396 / Investigate why systems skipped in quarterly patching

Update YUM cache

---

uclalib_packer.yml

A defined string resolves to "true" in a boolean context, even when the value is "false"
The `bool` filter resolves the string "false" to a boolean "false"

Force type casting

---

.ansible-lint

Skipping the nit-pickier checks
- FQCN (we are still on ansible 2.9.27)
- Task names begin with capital letter (nice, but, unnecessary)

Add linting rules

---

californica/uclalib_californica_backup.yml

Breaking change with MySQL 5.7
Resolves
mysqldump: Error: 'Access denied; you need (at least one of) the
PROCESS privilege(s) for this operation' when trying to dump
tablespaces
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html#mysqld-5-7-31-security https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-21.html#mysqld-8-0-21-security

Skip dumping tablespaces

---

uclalib_vmware_snapshot.yml
uclalib_vmware_snapshot_report.yml

Not all hosts discover the same python, causing connection: local to use the wrong (non-existant) python interpreter.

Use correct python interpreter

---

uclalib_vmware_snapshot_report.yml

%z in python3 is ±HHMM[SS[.ffffff]
%:z in 3.12+ is ±HH:MM[:SS[.ffffff]] (note the added colons, in accordance with ISO 8601)
https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

Prepare for newer python

---

uclalib_vmware_snapshot_report.yml

- Read entire report in
- Display report, without looping
- prevents record duplication
- Display location of report path

Clean up ansible output
